In [1]:
import numpy as np

In [6]:
from numpy import linalg


### Задание 1
Создайте numpy array с элементами от числа N до 0   
(например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [2]:
N = 10

In [3]:
a = np.arange(N)[::-1]
a


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

### Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [4]:
matrix = np.diag(np.arange(N)[::-1])
matrix


array([[9, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 8, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 7, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 6, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [5]:
matrix_sum = np.sum(np.diagonal(matrix))
matrix_sum


45

### Задание 3
Решите систему уравнений:  
4x + 2y + z = 4  
x + 3y = 12  
5y + 4z = -3


In [7]:
a = np.matrix([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
b = np.array([4, 12, -3])


In [8]:
c = linalg.solve(a, b)
c


array([ 0.46666667,  3.84444444, -5.55555556])

### Задание 4
Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем.  

На сайт заходит очередной посетитель, о покупках которого известно следующее:  
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя.
Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats


In [9]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ],
    np.int32
)


In [10]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])


In [11]:
def cos(a, b):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """

    aLength = np.linalg.norm(a)
    bLength = np.linalg.norm(b)

    return np.dot(a, b) / (aLength * bLength)


In [13]:
users_comparison = []
for user in users_stats:
    angle = np.arccos(cos(user, next_user_stats))
    users_comparison.append(angle)


In [14]:
min_value = np.amin(np.array(users_comparison))


In [15]:
similar_user_index = users_comparison.index(min_value)
similar_user_index


7